### ISSUE TITLE
Add dynamic data structure for supported thorlab cube devices

### ISSUE THREAD

**Issue by armaanrasheed** [quantumion/thorlabs_cube#26]
Currently, statically typed comments indicate which devices exist in our ecosystem requiring a change everytime a new one is added. Make a dictionary based device data structure that can contain all of these device names and be dynamically called from the `aqctl_thorlabs_cube.py` file and elsewhere.

From Issue #20 

![image](https://github.com/user-attachments/assets/0d97c04b-82a9-41b9-96ef-e1c70042364c)

**Comment by collineps** [comment]
https://github.com/quantumion/thorlabs_cube/pull/20#discussion_r1793617938
